### Imports

In [30]:
%run CNN_LSTM.ipynb

In [31]:
# lista_estacoes = ["campo_grande", "curitiba", "manaus", "minas_gerais_gv", "mossoro", "pelotas", "brasilia", "minas_gerais_bh"]
lista_estacoes = ["brasilia"]
janela_tempo = 12
results_cnn_lstm = {}
results_cnn_bilstm = {}

In [32]:
for estacao in lista_estacoes:
    # anual_df = load_and_filter(estacao, 7, 18, False).set_index("data_hora")
    raw_anual_df = pd.read_csv("../data/brasilia_full.csv", sep=";")
    anual_df = pre_processing(raw_anual_df)
    
    anual_df["hora"] = anual_df["data_hora"].dt.hour
    anual_df = filter_between(anual_df, "hora", 7, 18)
    results_cnn_lstm[estacao] = {}
    results_cnn_bilstm[estacao] = {}
    
    # LSTM
    process_cnn_lstm(1, estacao, anual_df, results_cnn_lstm, False, False)

    # BiLSTM
    # process_cnn_lstm(5, estacao, anual_df, results_cnn_bilstm, False, True)

Starting process 0 for station brasilia with LSTM type

In [33]:
list_df_results = []
for estacao in lista_estacoes:
    list_df_results.append(create_table_results(estacao, "lstm", results_cnn_lstm[estacao]))
    # list_df_results.append(create_table_results(estacao, "bilstm", results_cnn_bilstm[estacao]))

In [34]:
df_final = pd.concat(list_df_results, axis=0)

In [35]:
df_final.groupby(level=[0, 1]).mean().reset_index()

    estacao tipo_rede       mse      rmse       mae        r2
0  brasilia      lstm  0.828617  0.910284  0.595589  0.332335

In [7]:
pd.set_option('display.max_rows', 100)

In [9]:
df_final

                                         mse      rmse       mae        r2
estacao         tipo_rede execucao
campo_grande    lstm      1         0.195169  0.441779  0.322466  0.762519
                          2         0.179613  0.423808  0.291746  0.805789
                          3         0.181333  0.425832  0.277353  0.808751
                          4         0.186960  0.432389  0.301955  0.769109
                          5         0.158215  0.397763  0.257647  0.843244
                bilstm    1         0.166800  0.408412  0.268452  0.832192
                          2         0.165902  0.407311  0.275731  0.813647
                          3         0.203750  0.451387  0.338301  0.753892
                          4         0.160610  0.400762  0.257303  0.845991
                          5         0.179950  0.424205  0.291540  0.815177
curitiba        lstm      1         0.172227  0.415003  0.285368  0.771611
                          2         0.224101  0.473393  0.348963  0.727099
                          3         0.188041  0.433637  0.296678  0.766381
                          4         0.164400  0.405462  0.276035  0.801881
                          5         0.195001  0.441590  0.310929  0.755265
                bilstm    1         0.172240  0.415018  0.278448  0.815180
                          2         0.178978  0.423057  0.291707  0.803961
                          3         0.158165  0.397699  0.261314  0.820840
                          4         0.162495  0.403107  0.267527  0.785272
                          5         0.189014  0.434758  0.295083  0.728017
manaus          lstm      1         0.212396  0.460864  0.324008  0.657936
                          2         0.192747  0.439030  0.305673  0.727813
                          3         0.209271  0.457461  0.316101  0.747895
                          4         0.199980  0.447191  0.296851  0.735720
                          5         0.222026  0.471196  0.326465  0.739489
                bilstm    1         0.208585  0.456711  0.310383  0.695047
                          2         0.205892  0.453753  0.305732  0.729946
                          3         0.203584  0.451203  0.298742  0.775277
                          4         0.191579  0.437697  0.294685  0.746604
                          5         0.193015  0.439334  0.290851  0.746545
minas_gerais_gv lstm      1         0.278138  0.527388  0.399015  0.629170
                          2         0.295621  0.543711  0.411379  0.665577
                          3         0.203870  0.451520  0.320126  0.790829
                          4         0.192581  0.438840  0.309137  0.813179
                          5         0.194981  0.441567  0.312158  0.780941
                bilstm    1         0.191244  0.437315  0.303384  0.822906
                          2         0.185715  0.430946  0.293631  0.818675
                          3         0.181891  0.426486  0.291124  0.825708
                          4         0.185404  0.430585  0.302572  0.809573
                          5         0.242860  0.492808  0.371581  0.677238
mossoro         lstm      1         0.060822  0.246622  0.166079  0.927850
                          2         0.053852  0.232060  0.154755  0.933673
                          3         0.043823  0.209340  0.134343  0.946617
                          4         0.057837  0.240494  0.156519  0.927812
                          5         0.063818  0.252622  0.195970  0.921112
                bilstm    1         0.042478  0.206103  0.136401  0.946416
                          2         0.044721  0.211474  0.137317  0.945997
                          3         0.046872  0.216500  0.144527  0.943780
                          4         0.041095  0.202719  0.131673  0.948397
                          5         0.053854  0.232065  0.164728  0.940926
pelotas         lstm      1         0.132560  0.364088  0.250737  0.858343
                          2         0.135978  0.368752  0.255630  0.867175
                          3         0.125091  0.353682  0.243655  0.877811
                          4         0.196580  0.443373  0.316628  0.724709
                          5         0.191613  0.437736  0.326968  0.812500
                bilstm    1         0.152775  0.390865  0.275831  0.828818
                          2         0.123058  0.350796  0.237936  0.874839
                          3         0.157425  0.396768  0.302122  0.802894
                          4         0.118590  0.344369  0.235822  0.885670
                          5         0.130770  0.361621  0.256893  0.854204
brasilia        lstm      1         0.230321  0.479918  0.320720  0.732681
                          2         0.241756  0.491687  0.357268  0.729810
                          3         0.233967  0.483701  0.317640  0.756581
                          4         0.297477  0.545415  0.406204  0.624807
                          5         0.236577  0.486391  0.301286  0.775372
                bilstm    1         0.238006  0.487858  0.351501  0.726522
                          2         0.215324  0.464031  0.286807  0.773998
                          3         0.192419  0.438656  0.267347  0.809120
                          4         0.221362  0.470492  0.297202  0.745433
                          5         0.207716  0.455758  0.289261  0.803297
minas_gerais_bh lstm      1         0.170606  0.413045  0.288082  0.780415
                          2         0.162886  0.403591  0.279038  0.793329
                          3         0.151310  0.388986  0.257362  0.836515
                          4         0.135628  0.368277  0.233583  0.858162
                          5         0.142693  0.377747  0.239004  0.847388
                bilstm    1         0.133674  0.365614  0.231120  0.856019
                          2         0.152421  0.390411  0.255399  0.829204
                          3         0.150345  0.387744  0.251917  0.820745
                          4         0.148726  0.385650  0.252013  0.836738
                          5         0.166740  0.408338  0.278730  0.855413