### Imports

In [1]:
%run LSTM.ipynb

2025-07-24 18:49:31.484632: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-07-24 18:49:36.161223: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-07-24 18:49:36.167344: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-07-24 18:49:44.931186: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
lista_estacoes = ["campo_grande", "curitiba", "manaus", "minas_gerais_gv", "mossoro", "pelotas", "brasilia", "minas_gerais_bh"]

janela_tempo = 12
results_lstm = {}
results_bilstm = {}

In [3]:
for estacao in lista_estacoes:
    anual_df = load_and_filter(estacao, 7, 18, True).set_index("data_hora")

    train_size = int(0.7 * (round(len(anual_df)/10)*10))

    train_df = anual_df.iloc[0:train_size]
    test_df = anual_df.iloc[train_size:]
    
    results_lstm[estacao] = {}
    results_bilstm[estacao] = {}

    # LSTM
    process_lstm(5, estacao, train_df, test_df, results_lstm, True, False, False)

    # BiLSTM
    process_lstm(5, estacao, train_df, test_df, results_bilstm, True, True, False)

Starting process 0 for station campo_grande with LSTM type

2025-07-24 18:50:03.106505: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

Starting process 1 for station campo_grande with LSTM type
Starting process 2 for station campo_grande with LSTM type
Starting process 3 for station campo_grande with LSTM type
Starting process 4 for station campo_grande with LSTM type
Starting process 0 for station campo_grande with BiLSTM type
Starting process 1 for station campo_grande with BiLSTM type
Starting process 2 for station campo_grande with BiLSTM type
Starting process 3 for station campo_grande with BiLSTM type
Starting process 4 for station campo_grande with BiLSTM type
Starting process 0 for station curitiba with LSTM type
Starting process 1 for station curitiba with LSTM type
Starting process 2 for station curitiba with LSTM type
Starting process 3 for station curitiba with LSTM type
Starting process 4 for station curitiba with LSTM type
Starting process 0 for station curitiba with BiLSTM type
Starting process 1 for station curitiba with BiLSTM type
Starting process 2 for station curitiba with BiLSTM type
Starting process 3 for station curitiba with BiLSTM type
Starting process 4 for station curitiba with BiLSTM type
Starting process 0 for station manaus with LSTM type
Starting process 1 for station manaus with LSTM type
Starting process 2 for station manaus with LSTM type
Starting process 3 for station manaus with LSTM type
Starting process 4 for station manaus with LSTM type
Starting process 0 for station manaus with BiLSTM type
Starting process 1 for station manaus with BiLSTM type
Starting process 2 for station manaus with BiLSTM type
Starting process 3 for station manaus with BiLSTM type
Starting process 4 for station manaus with BiLSTM type
Starting process 0 for station minas_gerais_gv with LSTM type
Starting process 1 for station minas_gerais_gv with LSTM type
Starting process 2 for station minas_gerais_gv with LSTM type
Starting process 3 for station minas_gerais_gv with LSTM type
Starting process 4 for station minas_gerais_gv with LSTM type
Starting process 0 for station minas_gerais_gv with BiLSTM type
Starting process 1 for station minas_gerais_gv with BiLSTM type
Starting process 2 for station minas_gerais_gv with BiLSTM type
Starting process 3 for station minas_gerais_gv with BiLSTM type
Starting process 4 for station minas_gerais_gv with BiLSTM type
Starting process 0 for station mossoro with LSTM type
Starting process 1 for station mossoro with LSTM type
Starting process 2 for station mossoro with LSTM type
Starting process 3 for station mossoro with LSTM type
Starting process 4 for station mossoro with LSTM type
Starting process 0 for station mossoro with BiLSTM type
Starting process 1 for station mossoro with BiLSTM type
Starting process 2 for station mossoro with BiLSTM type
Starting process 3 for station mossoro with BiLSTM type
Starting process 4 for station mossoro with BiLSTM type
Starting process 0 for station pelotas with LSTM type
Starting process 1 for station pelotas with LSTM type
Starting process 2 for station pelotas with LSTM type
Starting process 3 for station pelotas with LSTM type
Starting process 4 for station pelotas with LSTM type
Starting process 0 for station pelotas with BiLSTM type
Starting process 1 for station pelotas with BiLSTM type
Starting process 2 for station pelotas with BiLSTM type
Starting process 3 for station pelotas with BiLSTM type
Starting process 4 for station pelotas with BiLSTM type
Starting process 0 for station brasilia with LSTM type
Starting process 1 for station brasilia with LSTM type
Starting process 2 for station brasilia with LSTM type
Starting process 3 for station brasilia with LSTM type
Starting process 4 for station brasilia with LSTM type
Starting process 0 for station brasilia with BiLSTM type
Starting process 1 for station brasilia with BiLSTM type
Starting process 2 for station brasilia with BiLSTM type
Starting process 3 for station brasilia with BiLSTM type
Starting process 4 for station brasilia with BiLSTM type
Starting process 0 for station minas_gerais_bh with LSTM type
Starting process 1 for station minas_gerais_bh with LSTM type
Starting process 2 for station minas_gerais_bh with LSTM type
Starting process 3 for station minas_gerais_bh with LSTM type
Starting process 4 for station minas_gerais_bh with LSTM type
Starting process 0 for station minas_gerais_bh with BiLSTM type
Starting process 1 for station minas_gerais_bh with BiLSTM type
Starting process 2 for station minas_gerais_bh with BiLSTM type
Starting process 3 for station minas_gerais_bh with BiLSTM type
Starting process 4 for station minas_gerais_bh with BiLSTM type

In [4]:
list_df_results = []
for estacao in lista_estacoes:
    list_df_results.append(create_table_results(estacao, "lstm", results_lstm[estacao]))
    list_df_results.append(create_table_results(estacao, "bilstm", results_bilstm[estacao]))

In [5]:
df_final = pd.concat(list_df_results, axis=0)

In [6]:
df_final.groupby(level=[0, 1]).mean().reset_index()

            estacao tipo_rede       mse      rmse       mae        r2
0          brasilia    bilstm  0.204673  0.451542  0.306433  0.778125
1          brasilia      lstm  0.199410  0.441836  0.322564  0.782548
2      campo_grande    bilstm  0.149490  0.386624  0.249384  0.846520
3      campo_grande      lstm  0.191180  0.435189  0.336680  0.802041
4          curitiba    bilstm  0.165272  0.404428  0.293640  0.792469
5          curitiba      lstm  0.196653  0.432892  0.331940  0.756054
6            manaus    bilstm  0.253882  0.494776  0.386288  0.643699
7            manaus      lstm  0.175155  0.417740  0.294585  0.775280
8   minas_gerais_bh    bilstm  0.130070  0.358908  0.253060  0.847450
9   minas_gerais_bh      lstm  0.214799  0.454069  0.372302  0.716411
10  minas_gerais_gv    bilstm  0.152578  0.390556  0.267219  0.845639
11  minas_gerais_gv      lstm  0.228805  0.466385  0.366744  0.775617
12          mossoro    bilstm  0.079356  0.270091  0.218836  0.903711
13          mossoro      lstm  0.086220  0.281390  0.238731  0.894342
14          pelotas    bilstm  0.133855  0.364669  0.255198  0.869281
15          pelotas      lstm  0.204977  0.435482  0.336833  0.787816

In [7]:
pd.set_option('display.max_rows', 100)

In [8]:
df_final

                                         mse      rmse       mae        r2
estacao         tipo_rede execucao
campo_grande    lstm      1         0.148340  0.385149  0.274197  0.824906
                          2         0.158149  0.397680  0.281798  0.844775
                          3         0.244655  0.494626  0.415666  0.738331
                          4         0.223571  0.472833  0.377010  0.766330
                          5         0.181183  0.425656  0.334727  0.835863
                bilstm    1         0.151351  0.389039  0.246359  0.852309
                          2         0.151962  0.389823  0.256078  0.842350
                          3         0.150434  0.387858  0.255573  0.843269
                          4         0.148974  0.385972  0.245611  0.852283
                          5         0.144727  0.380430  0.243302  0.842386
curitiba        lstm      1         0.122127  0.349466  0.235274  0.841394
                          2         0.200998  0.448328  0.364401  0.729856
                          3         0.128444  0.358391  0.239912  0.835652
                          4         0.374885  0.612279  0.536730  0.584416
                          5         0.156814  0.395997  0.283383  0.788952
                bilstm    1         0.159325  0.399155  0.278019  0.781393
                          2         0.235708  0.485498  0.403861  0.697411
                          3         0.146788  0.383129  0.255727  0.840619
                          4         0.144001  0.379474  0.276441  0.806675
                          5         0.140537  0.374883  0.254153  0.836249
manaus          lstm      1         0.219167  0.468153  0.343897  0.722219
                          2         0.158878  0.398595  0.271261  0.785096
                          3         0.165586  0.406922  0.288846  0.759922
                          4         0.167400  0.409146  0.293010  0.812186
                          5         0.164744  0.405886  0.275909  0.796976
                bilstm    1         0.177342  0.421120  0.285422  0.754663
                          2         0.163610  0.404488  0.288193  0.760599
                          3         0.261723  0.511589  0.401198  0.666840
                          4         0.449031  0.670098  0.583358  0.287669
                          5         0.217704  0.466588  0.373268  0.748726
minas_gerais_gv lstm      1         0.446372  0.668111  0.582487  0.533711
                          2         0.178596  0.422606  0.334592  0.830882
                          3         0.145657  0.381651  0.262358  0.858999
                          4         0.148366  0.385182  0.258760  0.872673
                          5         0.225033  0.474377  0.395523  0.781822
                bilstm    1         0.153672  0.392010  0.271109  0.837278
                          2         0.148415  0.385246  0.257698  0.860590
                          3         0.155682  0.394565  0.264429  0.850156
                          4         0.159826  0.399783  0.273590  0.837272
                          5         0.145295  0.381176  0.269271  0.842897
mossoro         lstm      1         0.091226  0.302036  0.262207  0.904850
                          2         0.042255  0.205560  0.152278  0.948860
                          3         0.060109  0.245171  0.206187  0.929772
                          4         0.047794  0.218619  0.175299  0.948639
                          5         0.189717  0.435565  0.397684  0.739589
                bilstm    1         0.075142  0.274121  0.228103  0.900968
                          2         0.095317  0.308734  0.267315  0.883946
                          3         0.157518  0.396886  0.363191  0.814516
                          4         0.036890  0.192067  0.127981  0.955842
                          5         0.031914  0.178645  0.107590  0.963285
pelotas         lstm      1         0.449139  0.670178  0.597637  0.536983
                          2         0.117841  0.343280  0.242003  0.878666
                          3         0.114181  0.337906  0.221790  0.894195
                          4         0.142388  0.377344  0.277981  0.857190
                          5         0.201336  0.448705  0.344755  0.772045
                bilstm    1         0.115934  0.340491  0.221456  0.896511
                          2         0.178268  0.422218  0.334016  0.823712
                          3         0.129638  0.360052  0.240900  0.874138
                          4         0.120322  0.346874  0.240774  0.877246
                          5         0.125111  0.353711  0.238844  0.874798
brasilia        lstm      1         0.150002  0.387301  0.240970  0.840946
                          2         0.178132  0.422057  0.292257  0.767822
                          3         0.170360  0.412747  0.293186  0.804482
                          4         0.323800  0.569034  0.486471  0.662629
                          5         0.174758  0.418040  0.299939  0.836860
                bilstm    1         0.192877  0.439178  0.269521  0.790310
                          2         0.210365  0.458656  0.336710  0.737580
                          3         0.180374  0.424704  0.261773  0.795426
                          4         0.186978  0.432410  0.273357  0.790182
                          5         0.252768  0.502761  0.390805  0.777128
minas_gerais_bh lstm      1         0.205757  0.453605  0.369450  0.691562
                          2         0.121008  0.347862  0.241714  0.857729
                          3         0.241209  0.491131  0.425559  0.706509
                          4         0.137269  0.370498  0.278845  0.809185
                          5         0.368753  0.607251  0.545940  0.517071
                bilstm    1         0.113827  0.337383  0.213036  0.877894
                          2         0.155997  0.394964  0.298075  0.813159
                          3         0.166264  0.407754  0.332644  0.806394
                          4         0.102117  0.319557  0.200978  0.883438
                          5         0.112147  0.334883  0.220565  0.856367